version: "3"

services:
  site_visitor:
    build:
      context: .
    restart: always
    container_name: site_visitor
    environment:
      - SITE_VISIT_PERIOD=1 #in seconds
      - URLS=https://blog.m-ahadi.ir,https://m-ahadi.ir
      - USE_PROXY=True
      - LOG_LEVEL=info
      - PARALLELS=10
      - MINIMUM_VISIT=60  #in second
      - MAXIMUM_VISIT=100  #in second
