version: "3"

services:
  site_visitor:
    image: docker.pkg.github.com/m-ahadi/site_visitor/site_visitor:latest
    restart: always
    container_name: site_visitor
    environment:
      - SITE_VISIT_PERIOD=1 #in seconds
      - URL=https://botfun.ir
      - USE_PROXY=True
      - LOG_LEVEL=info
      - PARALLELS=3